# Generated by Django 2.2.19 on 2021-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20210324_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel_title',
        ),
    ]
